// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tokens.Models;

#nullable disable

namespace Tokens.Migrations
{
    [DbContext(typeof(DeptDbContext))]
    [Migration("20250819115915_token")]
    partial class token
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tokens.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            DeptName = "HR"
                        },
                        new
                        {
                            DeptId = 2,
                            DeptName = "IT"
                        },
                        new
                        {
                            DeptId = 3,
                            DeptName = "Finance"
                        });
                });

            modelBuilder.Entity("Tokens.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "amber@gmail.com",
                            Name = "Amber",
                            Password = "amber123",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "charan@g,mail.com",
                            Name = "Charan",
                            Password = "charan123",
                            Role = "User"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "hadiya@gmail.com",
                            Name = "Hadiya",
                            Password = "hadiya123",
                            Role = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
